### ISSUE TITLE
After upgrade to 4.0.1, xpub watch-only wallet works, zpub doesn't

### ISSUE THREAD

**Issue by thestick613** [BlueWallet/BlueWallet#490]
The first zpub wallet i tried to import shows 0 BTC after a few seconds of processing, and the second zpub wallet i tried to import hangs in the loading section. The animation keeps running but nothing happens. I let it run for a few minutes. These are wallets generated from electrum.

**Comment by Overtorment** [comment]
Takes a lot of time to import if there are many transactions. Will be
optimized in next versions.

**Comment by thestick613** [comment]
The 0 BTC wallet seems to have [this problem](https://github.com/BlueWallet/BlueWallet/commit/544a9e61f1a6353a64bd70455c0fe541cff3404a#diff-99546c308285ab02fd031605451b0daeR20). The gap between used addresses is larger than 3 for the first addresses. Will this patch also work on zpub addresses? If so, you could probably close this issue.

**Comment by Overtorment** [comment]
Latest PRs increased gap limit and significally speeded up rescan. Should be out in 4.0.2
Hope will solve that for you.

**Comment by thestick613** [comment]
The one shat showed 0 BTC now shows one transaction (a lot more are missing), and the one that loaded forever still loads forever, after upgrade to 4.0.2, so there's probably more work to be done.

**Comment by Overtorment** [comment]
How many transactions do you have there?
Transactions fetch for zpub is not batched yet.
Do you have any gaps?

Also, would be awesome if you could unload your btc somewhere else and provides used zpub so I could test and optimize things on it.

**Comment by pysiak** [comment]
A 1 transaction zpub import from electrum hangs and never completes. xpubs worked fine with few and lots of transactions. Took a little bit longer but completed.
I still see this on 4.0.2
How can I help debug?

**Comment by Overtorment** [comment]
Would help if you could send me privately this problematic zpub, i at
bluewallet dot io

**Comment by pysiak** [comment]
I'll send one when when I get the chance

**Comment by thestick613** [comment]
I think gap limit should be at least 100 for all the wallets.

**Comment by Overtorment** [comment]
should be fixed  in https://github.com/BlueWallet/BlueWallet/pull/514.
will rollout in v4.0.4

**Comment by thestick613** [comment]
The one that loaded forever now shows everything alright.
The one that showed only the first transaction still shows only the first transaction. I think the gap limit should be increased just a bit more to 50-100.

**Comment by Overtorment** [comment]
Can you delete faulty wallet and import it again? There are chances
internal state is kept from previous version.
Will increase gaplimit to 50 if this wont help. Also, later Ill add
gaplimit as per-wallet configuration for advanced users.

**Comment by thestick613** [comment]
I've deleted the faulty wallet and i've imported it again. I waited 10 minutes, but the progress wheel kept spinning. Is zpub optimised yet? If it's not, i guess it's normal.

**Comment by Overtorment** [comment]
@thestick613 zpubs should work through electrum server, and all requests are batched, so should be quite fast (~10 sec to import even a big one, assuming connection to electrum is ok). If smth is not right, can you send me a faulty zpub? i at bluewallet dot io

PS. in next versions electrum server address will be configurable in settings

**Comment by thestick613** [comment]
works now.
