### ISSUE TITLE
“Currency change” setting not working

### ISSUE THREAD

**Issue by Olugbo** [BlueWallet/BlueWallet#6147]
Noticed since the latest iOS update, I can’t seem to change the currency in my wallet. It appears to change on the settings page but the currency symbol and denomination amount doesn’t actually change. When I go back to settings, it’s back at the “default” currency. Same issue even after restart. 

* iPhone 14, iOS 17.3.1
* BW v6.5.3
* self-test passed

**Comment by WCTwine** [comment]
Same in Mac OSX

**Comment by marcosrdz** [comment]
Should be fixed in 6.5.4

**Comment by Olugbo** [comment]
Yes, fixed in iOS after update Sent from my iPhoneOn Feb 18, 2024, at 3:35 AM, Marcos Rodriguez Vélez ***@***.***> wrote:﻿
Should be fixed in 6.5.4

**Comment by diegorod** [comment]
This is still not fixed on android 6.5.5 . I have system language set to Portuguese and blue wallet to dollars but it is showing in Brazilian real
