### ISSUE TITLE
Compatibility with Electrum Wallet

### ISSUE THREAD

**Issue by dk-from-twitter** [BlueWallet/BlueWallet#825]
Hello,
I tried to use a cold storage laptop running Electrum for private key management together with importing the zpub in BlueWallet for receiving transactions and generating unsigned spending ones.
It doesn't work.
I get an error when I try to import the unsigned transaction from BlueWallet to the laptop using the laptop camera and scanning the QR code on the mobile.
I also get an error when I try to use the BlueWallet to broadcast a signed transaction from the laptop. It fails to decode the QR of the signed transaction from the laptop screen.

Thanks.
![IMG_2933](https://user-images.githubusercontent.com/48622801/73135016-80688800-4035-11ea-9dc6-9b800ef72603.jpeg)
![Screenshot from 2020-01-26 12-09-35](https://user-images.githubusercontent.com/48622801/73135017-80688800-4035-11ea-9b7e-b7debf3efaa2.png)

**Comment by Overtorment** [comment]
Hi! We are working hard on Coldcard integration. We made lots of progress, so your problem might have been fixed as well.
In particular, 'magic number' error looks like when youre trying to feed transaction hex to app when it actually expects base64 PSBT.

Anyway, you can try take latest apk build from https://github.com/BlueWallet/BlueWallet/pull/793 for Android, or wait for official 5.0.0 release.

**Comment by csensitive** [comment]
I can confirm the issue with transferring unsigned (or PSBT) transactions still persists and errors the exact same output as OP posted. I haven't tried importing a signed transaction from Ethereum desktop but my guess is it also fails due to same out-/input error.

**Comment by raytorres280** [comment]
Not sure if related, but I did receive PBST errors as a result of my master fingerprint not being imported correctly and having fingerprint '00000000'. Would be curious to see if this still occurs once #4693 is merged in.
